### ISSUE TITLE
Create Directory structure for Lstring library

### ISSUE THREAD

**Issue by TH-montassar** [TH-montassar/Lstring#4]

**Comment by HXH106** [comment]
Directory structure for a C library:

**build/:** A special directory that should not be considered part of the source of the project. Used for storing ephemeral build results. must not be checked into source control. If using source control, must be ignored using source control ignore-lists.
**src/:** Main compilable source location.
**include:/** Directory for public headers.
**tests:/** Directory for tests.
**examples:/** Directory for samples and examples.
